export const HUB_WALK_MASK_ATTRIBUTE = 'color_2';

export const HUB_POI_NAME_PREFIX = 'EMPTY_POI_';

export const HUB_WALK_MIN_SAMPLE_WEIGHT = 0.08;
export const HUB_WALK_SAMPLE_MAX_ATTEMPTS = 48;

export const HUB_COMPANION_WALK_SPEED = 1;
export const HUB_COMPANION_ARRIVAL_DISTANCE = 0.28;
export const HUB_COMPANION_MIN_SEPARATION = 1.5;
export const HUB_COMPANION_SEPARATION_STRENGTH = 2.5;

export const HUB_COMPANION_IDLE_MIN = 3;
export const HUB_COMPANION_IDLE_MAX = 10;
export const HUB_POI_IDLE_MIN = 5;
export const HUB_POI_IDLE_MAX = 15;

export const HUB_POI_DETECT_RADIUS = 9;
export const HUB_POI_VISIT_CHANCE = 0.38;

export const HUB_COMPANION_GROUND_OFFSET = 0;
